services:
  - type: web
    name: cafe-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generatedValue:
          baseOn: SECRET_KEY
